### PR TITLE
Add BERT to reading comprehension

### PR DESCRIPTION
**Pull request by dwhitena**
With this, DistilBERT is used by default for comprehension (from Hugging Face's transformers library). The BiDAF model can be used by setting the KATECHEO_COMP env var. 

Note, this still needs to be tested on a dev cluster.

### CODE REVIEW

**Comment by SebanSunny** [comment]
@dwhitena Should we return the name of the comprehension model as a meta data?

**Comment by dwhitena** [comment]
@SebanSunny Thanks for catching this. I think I fixed it, but let me know if it doesn't make sense.

**Comment by SebanSunny** [comment]
Looks good @dwhitena !

**Comment by SebanSunny** [comment]
@dwhitena We have new meta( 'on_topic' ) that we are checking for instead of "kb_article". This change needs to be updated in the **README.md** & **ReadingCom_Test.py** files.

**Pull request merged**
